### ISSUE TITLE
See it in action video is corrupt

### ISSUE THREAD

**Issue by frabjous** [TenderOwl/tenderowlcom#3]
The video located under the heading "See it in action" at:

[https://tenderowl.com/work/frog/](https://tenderowl.com/work/frog/)

does not work in Firefox. (It does seem to work in Chromium and Chromium-based browsers.)

Firefox reports it as corrupt. (Mozilla Firefox 97.0.1 on ArchLinux.)

**Comment by amka** [comment]
Moved the video to Youtube :)
